# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('ida', models.AutoField(primary_key=True, serialize=False)),
                ('nombrea', models.CharField(max_length=52)),
                ('direccion', models.CharField(max_length=60)),
                ('apuesta_min', models.IntegerField()),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loteria',
            fields=[
                ('idl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lot', models.CharField(max_length=52)),
                ('animalgroup', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticke_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apu', models.IntegerField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Animales')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('token', models.IntegerField()),
                ('nota', models.CharField(max_length=20)),
                ('ida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Agencia')),
                ('idl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Loteria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=52)),
                ('tipo', models.IntegerField()),
                ('usuarionombre', models.CharField(max_length=52)),
                ('contrasena', models.IntegerField()),
                ('id_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Agencia')),
            ],
        ),
        migrations.AddField(
            model_name='ticke_item',
            name='id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Ticket'),
        ),
        migrations.AddField(
            model_name='animales',
            name='idl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Loteria'),
        ),
    ]
