# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('ida', models.AutoField(primary_key=True, serialize=False)),
                ('nombrea', models.CharField(max_length=52)),
                ('direccion', models.CharField(max_length=60)),
                ('apuesta_min', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalGanador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Animales')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loteria',
            fields=[
                ('idl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lot', models.CharField(max_length=52)),
                ('bankporc', models.IntegerField(default=10)),
                ('agencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticke_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apu', models.IntegerField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Animales')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(null=True)),
                ('cedula', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('nota', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('ida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Agencia')),
                ('idl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Loteria')),
            ],
        ),
        migrations.AddField(
            model_name='ticke_item',
            name='id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Ticket'),
        ),
        migrations.AddField(
            model_name='horas',
            name='horas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.Sorteo'),
        ),
        migrations.AddField(
            model_name='horas',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.Ticket'),
        ),
        migrations.AddField(
            model_name='animalganador',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Sorteo'),
        ),
        migrations.AddField(
            model_name='animales',
            name='idl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Loteria'),
        ),
    ]
