# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteria',
            name='animalgroup',
            field=models.IntegerField(null=True),
        ),
    ]
