# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20171002_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteria',
            name='animalgroup',
        ),
    ]
