# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_remove_loteria_animalgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='animales',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
