# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_animales_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteria',
            name='idagencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.Agencia'),
        ),
    ]
