# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20171006_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteria',
            old_name='idagencia',
            new_name='agencia',
        ),
    ]
