# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_auto_20171006_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenciauser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Agenciauser',
        ),
    ]
