# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_auto_20171006_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteria',
            name='agencia',
        ),
    ]
