# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_auto_20171006_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenciauser',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenciauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
