# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_auto_20171006_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenciauser',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
