# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0015_auto_20171006_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
    ]
