# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0018_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
