# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0019_auto_20171017_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
