# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0021_horas_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
