# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0022_auto_20171018_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='numero',
            field=models.CharField(max_length=2),
        ),
    ]
