# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0023_auto_20171023_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
