# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0024_auto_20171024_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGanador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Animales')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Sorteo')),
            ],
        ),
    ]
