# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0026_auto_20171101_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horas',
            name='horas',
        ),
    ]
