# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0027_remove_horas_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='horas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.Sorteo'),
        ),
    ]
